### ISSUE TITLE
PPO with determinate variance 

### ISSUE THREAD

**Issue by keinccgithub** [nikhilbarhate99/PPO-PyTorch#44]
When I am looking deeply into your codes, I am curious about why you choose to decay the variance of actor network?
We know that one of advantages of PPO is the stochastic policy it uses, and I just don't know why you set a determinate variance even though it decaying?
Thanks!

**Comment by Alex-HaochenLi** [comment]
> When I am looking deeply into your codes, I am curious about why you choose to decay the variance of actor network?
> We know that one of advantages of PPO is the stochastic policy it uses, and I just don't know why you set a determinate variance even though it decaying?
> Thanks!

I have the same question with you. On the website I cannot find relevant material.

**Comment by frettini** [comment]
My intuition is that we want to have a high variance at the start so that the policy can explore different possible actions. As the policy is learning, the variance is reduced to narrow down the exploration path and hopefully find the optimal behaviour. I'm still very much trying to understand it as well so it would be great if someone can actually explain it.

**Comment by nikhilbarhate99** [comment]
In my experiments I found that a constant variance (decaying linearly) is easily trainable, similar intuition as mentioned by @frettini. Most other implementations parametrize variance too, so the network predicts it. (I might add this in future, if I get time)

**Comment by nihao-zhangtongxue** [comment]
I think the loss expression should not subtract entropy if there is a definite variance, because entropy is fixed at this point

**Comment by ZhangShaungnj** [comment]
> I think the loss expression should not subtract entropy if there is a definite variance, because entropy is fixed at this point

I wonder whether the variance should be generated by PPO or just definitely setted. Thanks!

**Comment by nihao-zhangtongxue** [comment]
Hi, The variance in the code is gradually annealed with iteration, and I think that the entropy of action distribution depends on the variance, so it makes me think that the entropy in the loss fun is no use.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nikhilbarhate99/PPO-PyTorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年1月13日(星期一) 晚上9:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nikhilbarhate99/PPO-PyTorch] PPO with determinate variance  (#44)





  
I think the loss expression should not subtract entropy if there is a definite variance, because entropy is fixed at this point
  
I wonder whether the variance should be generated by PPO or just definitely setted. Thanks!
